### PR TITLE
Does not return removed commands

### LINKED ISSUE #523: Remap / rebind keymap to action
**Describe the bug**
It does not seem possible to remap a kemap (like C-p which is bind to "SelectPreviousOrScrollUp") to an action (like "AddToPlaylist").

**To Reproduce**
I have this **keymap.toml**

```
[[keymaps]]
command = "SelectPreviousOrScrollUp"
key_sequence = "k"

[[actions]]
action = "AddToPlaylist"
key_sequence = "C-p"
```

**Expected behaviour**
SelectPreviousOrScrollUp is k
AddToPlaylist is C-p

**Environment**

- OS: Linux Fedora 40
- Application version: 0.19.1

### PR DESCRIPTION
**Pull request by arouene**
Commands set to None to remove the keybinding, where immediately returned by **find_command_or_action_from_key_sequence** on l.418.
Instead of looking for action keybinding.

Fix #523

### CODE REVIEW

File: spotify_player/src/config/keymap.rs [hunk 1]
```diff
@@ -397,6 +397,7 @@ impl KeymapConfig {
         self.keymaps
             .iter()
             .find(|&keymap| keymap.key_sequence == *key_sequence)
+            .filter(|keymap| keymap.command != Command::None)
```
Comment (aome510) [inline spotify_player/src/config/keymap.rs:400]: you can include this condition in `find`, e.g `keymap.key_sequence == *key_sequence && keymap.command != Command::None`

Comment (arouene) [reply spotify_player/src/config/keymap.rs]: It was a stylistic preference :D, but if you prefer the other way, it's also fine.

**Review by aome510 — APPROVED** [review]
