### PR TITLE
[Windows]: Create dummy window to handle media control

### LINKED ISSUE #259: [Windows]: Media control not working
**Describe the bug**
The media control keys on my keyboard seem to do nothing. 

**To Reproduce**

1. Download the Windows binary from the Releases page.
2. Use the following config file. 
3. Run the binary and play a song.
4. Use the media keys to play/pause.

_Config file:_
```toml
theme = "dracula"
client_id = "<REDACTED>"
client_port = 8080
playback_format = """
{track} • {artists}
{album}
{metadata}"""
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
track_table_item_max_len = 32
play_icon = "▶"
pause_icon = "▌▌"
liked_icon = "♥"
border_type = "Double"
progress_bar_type = "Line"
playback_window_position = "Bottom"
playback_window_width = 6
enable_media_control = true
enable_streaming = true
enable_cover_image_cache = true
default_device = "Spotify-Terminal"

[copy_command]
command = "clip"
args = []

[device]
name = "Spotify-Terminal"
device_type = "speaker"
volume = 100
bitrate = 320
audio_cache = false
```

**Expected behavior**
I expect the play/pause keys to work.

**Log**

```log
2023-09-29T01:09:56.495747Z  INFO spotify_player: General configurations: AppConfig { theme: "dracula", client_id: "783de5fb8de844a5bc53b14637c71cb6", client_port: 8080, copy_command: Command { command: "clip", args: [] }, playback_format: "{track} • {artists}\n{album}\n{metadata}", tracks_playback_limit: 50, proxy: None, ap_port: None, app_refresh_duration_in_ms: 32, playback_refresh_duration_in_ms: 0, page_size_in_rows: 20, track_table_item_max_len: 32, play_icon: "▶", pause_icon: "▌▌", liked_icon: "♥", border_type: Double, progress_bar_type: Line, playback_window_position: Bottom, playback_window_width: 6, enable_media_control: true, enable_streaming: true, enable_cover_image_cache: true, default_device: "Spotify-Terminal", device: DeviceConfig { name: "Spotify-Terminal", device_type: "speaker", volume: 100, bitrate: 320, audio_cache: false } }
2023-09-29T01:09:56.495860Z  INFO spotify_player: Theme configurations: ThemeConfig { themes: [Theme { name: "default", palette: Palette { background: None, foreground: None, black: Color { color: Black }, blue: Color { color: LightBlue }, cyan: Color { color: LightCyan }, green: Color { color: LightGreen }, magenta: Color { color: LightMagenta }, red: Color { color: LightRed }, white: Color { color: Gray }, yellow: Color { color: LightYellow }, bright_black: Color { color: DarkGray }, bright_white: Color { color: White }, bright_red: Color { color: Red }, bright_magenta: Color { color: Magenta }, bright_green: Color { color: Green }, bright_cyan: Color { color: Cyan }, bright_blue: Color { color: Blue }, bright_yellow: Color { color: Yellow } }, component_style: ComponentStyle { block_title: None, border: None, playback_track: None, playback_artists: None, playback_album: None, playback_metadata: None, playback_progress_bar: None, current_playing: None, page_desc: None, table_header: None, selection: None } }] }
2023-09-29T01:09:56.495887Z  INFO spotify_player: Keymap configurations: KeymapConfig { keymaps: [Keymap { key_sequence: KeySequence { keys: [None(Char('n'))] }, command: NextTrack }, Keymap { key_sequence: KeySequence { keys: [None(Char('p'))] }, command: PreviousTrack }, Keymap { key_sequence: KeySequence { keys: [None(Char('.'))] }, command: PlayRandom }, Keymap { key_sequence: KeySequence { keys: [None(Char(' '))] }, command: ResumePause }, Keymap { key_sequence: KeySequence { keys: [Ctrl(Char('r'))] }, command: Repeat }, Keymap { key_sequence: KeySequence { keys: [Ctrl(Char('s'))] }, command: Shuffle }, Keymap { key_sequence: KeySequence { keys: [None(Char('+'))] }, command: VolumeUp }, Keymap { key_sequence: KeySequence { keys: [None(Char('-'))] }, command: VolumeDown }, Keymap { key_sequence: KeySequence { keys: [None(Char('>'))] }, command: SeekForward }, Keymap { key_sequence: KeySequence { keys: [None(Char('<'))] }, command: SeekBackward }, Keymap { key_sequence: KeySequence { keys: [None(Enter)] }, command: ChooseSelected }, Keymap { key_sequence: KeySequence { keys: [None(Char('r'))] }, command: RefreshPlayback }, Keymap { key_sequence: KeySequence { keys: [None(Char('/'))] }, command: Search }, Keymap { key_sequence: KeySequence { keys: [None(Char('z'))] }, command: Queue }, Keymap { key_sequence: KeySequence { keys: [None(Char('Z'))] }, command: AddSelectedItemToQueue }, Keymap { key_sequence: KeySequence { keys: [Ctrl(Char(' '))] }, command: ShowActionsOnSelectedItem }, Keymap { key_sequence: KeySequence { keys: [None(Char('g')), None(Char('a'))] }, command: ShowActionsOnSelectedItem }, Keymap { key_sequence: KeySequence { keys: [None(Char('a'))] }, command: ShowActionsOnCurrentTrack }, Keymap { key_sequence: KeySequence { keys: [None(Char('R'))] }, command: RestartIntegratedClient }, Keymap { key_sequence: KeySequence { keys: [None(Tab)] }, command: FocusNextWindow }, Keymap { key_sequence: KeySequence { keys: [None(BackTab)] }, command: FocusPreviousWindow }, Keymap { key_sequence: KeySequence { keys: [None(Char('T'))] }, command: SwitchTheme }, Keymap { key_sequence: KeySequence { keys: [None(Char('D'))] }, command: SwitchDevice }, Keymap { key_sequence: KeySequence { keys: [None(Char('u')), None(Char('p'))] }, command: BrowseUserPlaylists }, Keymap { key_sequence: KeySequence { keys: [None(Char('u')), None(Char('a'))] }, command: BrowseUserFollowedArtists }, Keymap { key_sequence: KeySequence { keys: [None(Char('u')), None(Char('A'))] }, command: BrowseUserSavedAlbums }, Keymap { key_sequence: KeySequence { keys: [None(Char('g')), None(Char(' '))] }, command: CurrentlyPlayingContextPage }, Keymap { key_sequence: KeySequence { keys: [None(Char('g')), None(Char('t'))] }, command: TopTrackPage }, Keymap { key_sequence: KeySequence { keys: [None(Char('g')), None(Char('r'))] }, command: RecentlyPlayedTrackPage }, Keymap { key_sequence: KeySequence { keys: [None(Char('g')), None(Char('y'))] }, command: LikedTrackPage }, Keymap { key_sequence: KeySequence { keys: [None(Char('g')), None(Char('l'))] }, command: LibraryPage }, Keymap { key_sequence: KeySequence { keys: [None(Char('g')), None(Char('s'))] }, command: SearchPage }, Keymap { key_sequence: KeySequence { keys: [None(Char('g')), None(Char('b'))] }, command: BrowsePage }, Keymap { key_sequence: KeySequence { keys: [None(Backspace)] }, command: PreviousPage }, Keymap { key_sequence: KeySequence { keys: [Ctrl(Char('q'))] }, command: PreviousPage }, Keymap { key_sequence: KeySequence { keys: [None(Char('?'))] }, command: OpenCommandHelp }, Keymap { key_sequence: KeySequence { keys: [Ctrl(Char('h'))] }, command: OpenCommandHelp }, Keymap { key_sequence: KeySequence { keys: [None(Char('q'))] }, command: Quit }, Keymap { key_sequence: KeySequence { keys: [Ctrl(Char('c'))] }, command: Quit }, Keymap { key_sequence: KeySequence { keys: [None(Esc)] }, command: ClosePopup }, Keymap { key_sequence: KeySequence { keys: [None(Char('j'))] }, command: SelectNextOrScrollDown }, Keymap { key_sequence: KeySequence { keys: [Ctrl(Char('n'))] }, command: SelectNextOrScrollDown }, Keymap { key_sequence: KeySequence { keys: [None(Down)] }, command: SelectNextOrScrollDown }, Keymap { key_sequence: KeySequence { keys: [None(Char('k'))] }, command: SelectPreviousOrScrollUp }, Keymap { key_sequence: KeySequence { keys: [Ctrl(Char('p'))] }, command: SelectPreviousOrScrollUp }, Keymap { key_sequence: KeySequence { keys: [None(Up)] }, command: SelectPreviousOrScrollUp }, Keymap { key_sequence: KeySequence { keys: [None(PageUp)] }, command: PageSelectPreviousOrScrollUp }, Keymap { key_sequence: KeySequence { keys: [Ctrl(Char('b'))] }, command: PageSelectPreviousOrScrollUp }, Keymap { key_sequence: KeySequence { keys: [None(PageDown)] }, command: PageSelectNextOrScrollDown }, Keymap { key_sequence: KeySequence { keys: [Ctrl(Char('f'))] }, command: PageSelectNextOrScrollDown }, Keymap { key_sequence: KeySequence { keys: [None(Char('g')), None(Char('g'))] }, command: SelectFirstOrScrollToTop }, Keymap { key_sequence: KeySequence { keys: [None(Home)] }, command: SelectFirstOrScrollToTop }, Keymap { key_sequence: KeySequence { keys: [None(Char('G'))] }, command: SelectLastOrScrollToBottom }, Keymap { key_sequence: KeySequence { keys: [None(End)] }, command: SelectLastOrScrollToBottom }, Keymap { key_sequence: KeySequence { keys: [None(Char('s')), None(Char('t'))] }, command: SortTrackByTitle }, Keymap { key_sequence: KeySequence { keys: [None(Char('s')), None(Char('a'))] }, command: SortTrackByArtists }, Keymap { key_sequence: KeySequence { keys: [None(Char('s')), None(Char('A'))] }, command: SortTrackByAlbum }, Keymap { key_sequence: KeySequence { keys: [None(Char('s')), None(Char('d'))] }, command: SortTrackByDuration }, Keymap { key_sequence: KeySequence { keys: [None(Char('s')), None(Char('D'))] }, command: SortTrackByAddedDate }, Keymap { key_sequence: KeySequence { keys: [None(Char('s')), None(Char('r'))] }, command: ReverseTrackOrder }, Keymap { key_sequence: KeySequence { keys: [Ctrl(Char('k'))] }, command: MovePlaylistItemUp }, Keymap { key_sequence: KeySequence { keys: [Ctrl(Char('j'))] }, command: MovePlaylistItemDown }] }
2023-09-29T01:09:57.171733Z  INFO spotify_player::auth: Successfully used the cached credentials to create a new session!
2023-09-29T01:09:57.172563Z  INFO spotify_player::token: Getting new authentication token...
2023-09-29T01:09:57.389431Z  INFO spotify_player::token: Got new token: Token { access_token: "BQCLZMQfJA0dRsdGxYkrw11_bvXuek4rV3JcwZV2bxmYGCH7Wm9HpIqTWgnSaCMhOnlWhd-ztTPOpJuoQxt9WIDSG-vU5ZNA2L-yPGEQR0ZYnmzoQy0WC7DPMjfBta4fEHCh1zk7qurRCUnB7N8ec2pIrij_qJJMcIh3MgimsXLMh730xiTOlTOoMLPXbxqc5_K3149aTYK5g8AexXtALKfh3zg_Bos7CS3zB2ySt3-o-y-_l0b4psiTwJZUqzbxnOpycFcDXbOvcylPGEdlPoylQnHOjtMNVpLaE79pX3o", expires_in: Duration { secs: 3600, nanos: 0 }, expires_at: Some(2023-09-29T02:09:57.389418400Z), refresh_token: None, scopes: {} }
2023-09-29T01:09:57.389745Z  INFO spotify_player::streaming: Application's connect configurations: ConnectConfig { name: "Spotify-Terminal", device_type: Speaker, initial_volume: Some(65535), has_volume_ctrl: true, autoplay: false }
2023-09-29T01:09:57.389910Z  INFO spotify_player::streaming: Initializing a new integrated player with device_id=d9a7d671-a59f-4a5a-8e65-93ec153b560a
2023-09-29T01:09:57.390239Z  INFO spotify_player::streaming: Starting an integrated Spotify player using librespot's spirc protocol
2023-09-29T01:09:57.475264Z  INFO spotify_player::streaming: Got an event from the integrated player: VolumeSet { volume: 65535 }
2023-09-29T01:09:57.642980Z  INFO spotify_player: No playback found on startup, trying to connect to an available device...
2023-09-29T01:09:57.643892Z  INFO spotify_player::cli::client: Starting a client socket at 127.0.0.1:8080
2023-09-29T01:09:57.646112Z  INFO spotify_player::media_control: Initializing application's media control event watcher...
2023-09-29T01:09:57.768409Z  INFO client_request{request=GetCurrentUser}: spotify_player::client: successfully handled the client request, took: 123ms
2023-09-29T01:09:57.869494Z  INFO client_request{request=GetCurrentPlayback}: spotify_player::client: successfully handled the client request, took: 224ms
2023-09-29T01:09:57.911049Z  INFO client_request{request=GetUserFollowedArtists}: spotify_player::client: successfully handled the client request, took: 266ms
2023-09-29T01:09:57.975644Z  INFO client_request{request=GetUserPlaylists}: spotify_player::client: successfully handled the client request, took: 330ms
2023-09-29T01:09:58.318370Z  INFO client_request{request=GetUserSavedAlbums}: spotify_player::client: successfully handled the client request, took: 673ms
2023-09-29T01:09:58.799979Z  INFO client_request{request=ConnectDevice(None)}: spotify_player::client: Available devices: [Device { id: Some("d9a7d671-a59f-4a5a-8e65-93ec153b560a"), is_active: false, is_private_session: false, is_restricted: false, name: "Spotify-Terminal", _type: Speaker, volume_percent: Some(100) }]
2023-09-29T01:09:58.800029Z  INFO client_request{request=ConnectDevice(None)}: spotify_player::client: Trying to connect to device (id=d9a7d671-a59f-4a5a-8e65-93ec153b560a)
2023-09-29T01:09:58.985783Z  INFO client_request{request=ConnectDevice(None)}: spotify_player::client: Connection succeeded (device_id=d9a7d671-a59f-4a5a-8e65-93ec153b560a)!
2023-09-29T01:09:58.985867Z  INFO client_request{request=ConnectDevice(None)}: spotify_player::client: successfully handled the client request, took: 1341ms
2023-09-29T01:09:58.986732Z  INFO spotify_player::streaming: Got an event from the integrated player: Started { play_request_id: 0, track_id: SpotifyId { id: 301469809747648126091827087917431058177, audio_type: Track }, position_ms: 215610 }
2023-09-29T01:09:58.986792Z  INFO spotify_player::streaming: Got an event from the integrated player: Loading { play_request_id: 0, track_id: SpotifyId { id: 301469809747648126091827087917431058177, audio_type: Track }, position_ms: 215610 }
2023-09-29T01:09:59.112494Z  INFO client_request{request=GetCurrentPlayback}: spotify_player::client: successfully handled the client request, took: 125ms
2023-09-29T01:09:59.119639Z  INFO client_request{request=GetCurrentPlayback}: spotify_player::client: successfully handled the client request, took: 132ms
2023-09-29T01:10:00.193399Z  INFO spotify_player::client: Retrieving an image from the file: C:\Users\Rashil\.cache/spotify-player\image\Out of Time-Hugo Kant-cover.jpg
2023-09-29T01:10:00.222650Z  INFO client_request{request=GetUserSavedTracks}: spotify_player::client: successfully handled the client request, took: 2578ms
2023-09-29T01:10:01.063296Z  INFO spotify_player::streaming: Got an event from the integrated player: Paused { play_request_id: 0, track_id: SpotifyId { id: 301469809747648126091827087917431058177, audio_type: Track }, position_ms: 215610, duration_ms: 282013 }
2023-09-29T01:10:01.230468Z  INFO client_request{request=GetCurrentPlayback}: spotify_player::client: successfully handled the client request, took: 167ms
2023-09-29T01:10:02.138642Z  INFO client_request{request=Player(ResumePause)}: spotify_player::client: successfully handled the client request, took: 154ms
2023-09-29T01:10:02.143731Z  INFO spotify_player::streaming: Got an event from the integrated player: VolumeSet { volume: 65535 }
2023-09-29T01:10:02.143809Z  INFO spotify_player::streaming: Got an event from the integrated player: Playing { play_request_id: 0, track_id: SpotifyId { id: 301469809747648126091827087917431058177, audio_type: Track }, position_ms: 215610, duration_ms: 282013 }
2023-09-29T01:10:02.144868Z  INFO spotify_player::streaming: Got an event from the integrated player: Playing { play_request_id: 0, track_id: SpotifyId { id: 301469809747648126091827087917431058177, audio_type: Track }, position_ms: 215610, duration_ms: 282013 }
2023-09-29T01:10:02.316990Z  INFO client_request{request=GetCurrentPlayback}: spotify_player::client: successfully handled the client request, took: 172ms
2023-09-29T01:10:02.317766Z  INFO client_request{request=GetCurrentPlayback}: spotify_player::client: successfully handled the client request, took: 172ms
2023-09-29T01:10:02.318893Z  INFO client_request{request=GetCurrentPlayback}: spotify_player::client: successfully handled the client request, took: 174ms
2023-09-29T01:10:38.266620Z  INFO spotify_player::streaming: Got an event from the integrated player: TimeToPreloadNextTrack { play_request_id: 0, track_id: SpotifyId { id: 301469809747648126091827087917431058177, audio_type: Track } }
2023-09-29T01:10:38.449693Z  INFO client_request{request=GetCurrentPlayback}: spotify_player::client: successfully handled the client request, took: 182ms
2023-09-29T01:10:39.192931Z  INFO spotify_player::streaming: Got an event from the integrated player: Preloading { track_id: SpotifyId { id: 249743806236078787970449798430455318711, audio_type: Track } }
2023-09-29T01:10:39.347613Z  INFO client_request{request=GetCurrentPlayback}: spotify_player::client: successfully handled the client request, took: 154ms
2023-09-29T01:11:08.130290Z  INFO spotify_player::streaming: Got an event from the integrated player: EndOfTrack { play_request_id: 0, track_id: SpotifyId { id: 301469809747648126091827087917431058177, audio_type: Track } }
2023-09-29T01:11:08.130479Z  INFO spotify_player::streaming: Got an event from the integrated player: Changed { old_track_id: SpotifyId { id: 301469809747648126091827087917431058177, audio_type: Track }, new_track_id: SpotifyId { id: 249743806236078787970449798430455318711, audio_type: Track } }
2023-09-29T01:11:08.130518Z  INFO spotify_player::streaming: Got an event from the integrated player: Playing { play_request_id: 1, track_id: SpotifyId { id: 249743806236078787970449798430455318711, audio_type: Track }, position_ms: 0, duration_ms: 290173 }
2023-09-29T01:11:08.298766Z  INFO client_request{request=GetCurrentPlayback}: spotify_player::client: successfully handled the client request, took: 168ms
2023-09-29T01:11:08.306860Z  INFO client_request{request=GetCurrentPlayback}: spotify_player::client: successfully handled the client request, took: 176ms
2023-09-29T01:11:08.307153Z  INFO client_request{request=GetCurrentPlayback}: spotify_player::client: successfully handled the client request, took: 176ms
2023-09-29T01:11:09.389640Z  INFO client_request{request=GetCurrentPlayback}: spotify_player::client: Retrieving an image from the file: C:\Users\Rashil\.cache/spotify-player\image\Out of Time-Hugo Kant-cover.jpg
2023-09-29T01:11:09.392064Z  INFO client_request{request=GetCurrentPlayback}: spotify_player::client: successfully handled the client request, took: 185ms
2023-09-29T01:15:28.818039Z  INFO spotify_player::streaming: Got an event from the integrated player: TimeToPreloadNextTrack { play_request_id: 1, track_id: SpotifyId { id: 249743806236078787970449798430455318711, audio_type: Track } }
2023-09-29T01:15:29.148566Z  INFO client_request{request=GetCurrentPlayback}: spotify_player::client: successfully handled the client request, took: 330ms
2023-09-29T01:15:29.883803Z  INFO spotify_player::streaming: Got an event from the integrated player: Preloading { track_id: SpotifyId { id: 92338623467995932484187839528256705047, audio_type: Track } }
2023-09-29T01:15:30.050816Z  INFO client_request{request=GetCurrentPlayback}: spotify_player::client: successfully handled the client request, took: 166ms
2023-09-29T01:15:58.540741Z  INFO spotify_player::streaming: Got an event from the integrated player: EndOfTrack { play_request_id: 1, track_id: SpotifyId { id: 249743806236078787970449798430455318711, audio_type: Track } }
2023-09-29T01:15:58.541062Z  INFO spotify_player::streaming: Got an event from the integrated player: Changed { old_track_id: SpotifyId { id: 249743806236078787970449798430455318711, audio_type: Track }, new_track_id: SpotifyId { id: 92338623467995932484187839528256705047, audio_type: Track } }
2023-09-29T01:15:58.541177Z  INFO spotify_player::streaming: Got an event from the integrated player: Playing { play_request_id: 2, track_id: SpotifyId { id: 92338623467995932484187839528256705047, audio_type: Track }, position_ms: 0, duration_ms: 301786 }
2023-09-29T01:15:58.768534Z  INFO client_request{request=GetCurrentPlayback}: spotify_player::client: successfully handled the client request, took: 227ms
2023-09-29T01:15:58.818556Z  INFO client_request{request=GetCurrentPlayback}: spotify_player::client: Retrieving an image from the file: C:\Users\Rashil\.cache/spotify-player\image\Out of Time-Hugo Kant-cover.jpg
2023-09-29T01:15:58.819257Z  INFO client_request{request=GetCurrentPlayback}: spotify_player::client: successfully handled the client request, took: 262ms
2023-09-29T01:15:58.834605Z  INFO client_request{request=GetCurrentPlayback}: spotify_player::client: successfully handled the client request, took: 293ms
2023-09-29T01:15:58.838561Z  INFO client_request{request=GetCurrentPlayback}: spotify_player::client: successfully handled the client request, took: 297ms
2023-09-29T01:17:01.518261Z  INFO client_request{request=Player(SeekTrack(Duration { secs: 144, nanos: 34000000 }))}: spotify_player::client: successfully handled the client request, took: 182ms
2023-09-29T01:17:01.533978Z  INFO spotify_player::streaming: Got an event from the integrated player: Playing { play_request_id: 2, track_id: SpotifyId { id: 92338623467995932484187839528256705047, audio_type: Track }, position_ms: 144034, duration_ms: 301786 }
2023-09-29T01:17:01.722757Z  INFO client_request{request=GetCurrentPlayback}: spotify_player::client: successfully handled the client request, took: 188ms
2023-09-29T01:17:09.817008Z  INFO client_request{request=Player(SeekTrack(Duration { secs: 20, nanos: 576000000 }))}: spotify_player::client: successfully handled the client request, took: 152ms
2023-09-29T01:17:09.827797Z  INFO spotify_player::streaming: Got an event from the integrated player: Playing { play_request_id: 2, track_id: SpotifyId { id: 92338623467995932484187839528256705047, audio_type: Track }, position_ms: 20576, duration_ms: 301786 }
2023-09-29T01:17:10.001574Z  INFO client_request{request=GetCurrentPlayback}: spotify_player::client: successfully handled the client request, took: 173ms
2023-09-29T01:17:15.995634Z  INFO client_request{request=Player(ResumePause)}: spotify_player::client: successfully handled the client request, took: 144ms
2023-09-29T01:17:16.003734Z  INFO spotify_player::streaming: Got an event from the integrated player: Paused { play_request_id: 2, track_id: SpotifyId { id: 92338623467995932484187839528256705047, audio_type: Track }, position_ms: 26991, duration_ms: 301786 }
2023-09-29T01:17:16.172787Z  INFO client_request{request=GetCurrentPlayback}: spotify_player::client: successfully handled the client request, took: 168ms
```

**Backtrace**
```log
Got a panic: PanicInfo {
    payload: Any { .. },
    message: Some(
        Windows media controls require an HWND in MediaControlsOptions.,
    ),
    location: Location {
        file: "C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\souvlaki-0.6.1\\src\\platform\\windows\\mod.rs",
        line: 51,
        col: 14,
    },
    can_unwind: true,
}

Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: BaseThreadInitThunk
  19: RtlUserThreadStart
```

**Environment**

- OS: Windows 11 Build 25941
- Application version: 0.15.0
- Application features: default features available in the release binary

### PR DESCRIPTION
**Pull request by rashil2000**
Closes #259 

The code is from the example in Souvlaki repository: https://github.com/Sinono3/souvlaki/blob/master/examples/print_events.rs

### CODE REVIEW

File: spotify_player/src/media_control.rs [hunk 1]
```diff
@@ -105,5 +114,116 @@ pub fn start_event_watcher(
...
         std::thread::sleep(refresh_duration);
+
+        // this must be run repeatedly by your program to ensure
+        // the Windows event queue is processed by your application
+        #[cfg(target_os = "windows")]
+        windows::pump_event_queue();
+    }
+}
+
+// demonstrates how to make a minimal window to allow use of media keys on the command line
```
Comment (aome510) [inline spotify_player/src/media_control.rs:125]: Can you add note here mentioning that the `windows` handling codes in this file is copied from https://github.com/Sinono3/souvlaki/blob/master/examples/print_events.rs?

**Review by aome510 — APPROVED** [review]
Thanks for taking a look into this and implementing a fix

File: spotify_player/src/media_control.rs (hunk 1 above)
Comment (rashil2000) [reply spotify_player/src/media_control.rs:125]: Done
